export const home = "/home";
export const bookMark = "bookmark";
// export const profileuser = `/:id`;
export const signup = "/signup";
export const signin = "/signin";
export const dashboard = "/";
export const tweets = "tweets";
export const t_r = "t_r";
export const likes = "likes";
